Completed html-tables exercise. - Charlie McCanna
cgmccanna/m1-0122-code-solutions pull request #8
Opened 2022-01-31 01:26 UTC by cgmccanna

![html-tables](https://user-images.githubusercontent.com/74582871/151727057-c820ca21-b937-4e32-a7c9-03487f59a1c0.png)

2022-01-31 14:51 UTC, Zhiwutian requested changes
small update needed!

2022-01-31 14:51 UTC, Zhiwutian commented on html-tables/index.html
> +      </thead>
make sure to include the `tbody` element also

2022-02-01 02:03 UTC, cgmccanna commented
![updated-html-tables](https://user-images.githubusercontent.com/74582871/151902766-5939892e-034d-490a-95c6-c9c857fa0267.png)

2022-02-01 02:09 UTC, Zhiwutian approved these changes
👍🏼

2022-02-01 02:30 UTC, merged